config/routes.rb
Rails.application.routes.draw do
  resources :entries
  resources :searches
  resources :subject_courses_relations
  resources :enrollments
  resources :sessions
  resources :users
  resources :courses
  resources :instructors
  resources :subjects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  get 'instructor', to: 'instructors#index'
  get 'course', to: 'courses#index'
  get 'subject', to: 'subjects#index'
  get 'user', to: 'user#index'

  get 'search', to: 'searches#new'
  get 'entry', to: 'entries#index'
  get 'enroll', to: 'enrollments#new'

  get  'signup',  to: 'users#new'

  post 'register', to: 'users#create'


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /enrollments
  # GET /enrollments.json
  def index
    @user ||= User.find_by(id: session[:user_id].to_i)

    @enrollments = @user.enrollments

    # @course_id = params[:course_id].to_i
    # @courses = Course.all.find_by(id: @course_id)

    # @course_id = params[:course_id].to_i
    #
    # @user ||= User.find_by(id: session[:user_id].to_i)
    # user_id = @user['id']
    # enroll = Enrollment.new
    # enroll.user_id = user_id
    # enroll.course_id = @course_id
    # enroll.save
    # @courses = Course.all.find_by(id: @course_id)
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @course_id = params[:course_id].to_i

    @user ||= User.find_by(id: session[:user_id].to_i)
    user_id = @user['id']
    enroll = Enrollment.new
    enroll.user_id = user_id
    enroll.course_id = @course_id
    enroll.save
    @courses = Course.find_by(id: @course_id)

  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)



    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:user_id, :course_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment, local: true) do |form| %>
  <% if enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :enrollment_user_id %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.text_field :course_id, id: :enrollment_course_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<% provide(:title, "Enrollment Successful") %>

<h1>Enrollments</h1>



<table class="table">
  <thead class="thead-default">
    <tr>
      <th>ID</th>
      <th>Code</th>
      <th>Name</th>
      <th>Description</th>
      <th>Credits</th>
    </tr>
  </thead>
  <tbody>

    <% @enrollments.each do |each_course| %>
      <tr>

        <% @course = Course.find_by(id: each_course.course_id) %>

        <% if !@course.nil? %>
          <tr>
            <th scope="row"><%= each_course.course_id %></th>
            <td><%= @course['code'] %></td>
            <td><%= @course['name'] %></td>
            <td><%= @course['description'] %></td>
            <td><%= @course['credit'] %></td>
            <td><button type="submit" class="btn btn-primary"><%= link_to 'Delete', each_course, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>

          </tr>
        <% end %>

      </tr>
    <% end %>

    <!-- <% @enrollments.each do |each_course| %>
      <tr>
        <th scope="row"><%= each_course['university_id'] %></th>
        <td><%= each_course['code'] %></td>
        <td><%= each_course['name'] %></td>
        <td><%= each_course['description'] %></td>
        <td><%= each_course['credit'] %></td>

      </tr>
    <% end %> -->
  </tbody>
</table>

app/views/enrollments/new.html.erb
<% provide(:title, "Enrollment Successful") %>

<h1>Enrollment Successful</h1>
<h1><%= @user['name']%></h1>



<table class="table">
  <thead class="thead-default">
    <tr>
      <th>ID</th>
      <th>Code</th>
      <th>Name</th>
      <th>Description</th>
      <th>Credits</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= @course_id%></th>
        <td><%= @courses['code'] %></td>
        <td><%= @courses['name'] %></td>
        <td><%= @courses['description'] %></td>
        <td><%= @courses['credit'] %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Back', searches_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @enrollment.user_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @enrollment.course_id %>
</p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>