config/routes.rb
Rails.application.routes.draw do
  resources :entries
  resources :searches
  resources :subject_courses_relations
  resources :enrollments
  resources :sessions
  resources :users
  resources :courses
  resources :instructors
  resources :subjects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  get 'instructor', to: 'instructors#index'
  get 'course', to: 'courses#index'
  get 'subject', to: 'subjects#index'
  get 'user', to: 'user#index'

  get 'search', to: 'searches#new'
  get 'entry', to: 'entries#index'
  get 'enroll', to: 'enrollments#new'

  get  'signup',  to: 'users#new'

  post 'register', to: 'users#create'


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json

  def index
    if logged_in?
      @user ||= User.find_by(id: session[:user_id])
      @courses = Course.search(params[:search])
      @subjects = Subject.all
    else
      redirect_to login_path
    end
    @subjects = Subject.all

    respond_to do |format|
      format.html
      format.js
    end
  end



  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    if logged_in?
      @user ||= User.find_by(id: session[:user_id])
      @courses = Course.search(params[:search])
      @subjects = Subject.all
    else
      redirect_to login_path
    end
    @subjects = Subject.all
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.fetch(:search, {})
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_with(model: search, local: true) do |form| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/searches/_modal.html.erb
<p id="notice"><%= notice %></p>

<%= javascript_include_tag "_search_controller" %>

<% course = params[:course] %>
<% subject_university_id = params[:subject] %>

<% if subject_university_id == "default" %>
  <% @result = Course.where("name LIKE ?", "%#{course}%") %>
<% end %>


<h1><br>Listing Courses</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Code</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |each_course| %>
      <tr>
        <th scope="row"><%= each_course['uni_id'] %></th>
        <td><%= each_course['code'] %></td>
        <td><%= each_course['name'] %></td>
        <td><%= each_course['description'] %></td>
        <td><%= each_course['credit'] %></td>

        <% if @user.nil? %>
          <form action="/login" method="GET">
            <td><button type="submit" class="btn btn-primary">Login Please</button></td>
          </form>
        <% else %>
          <form action="/enroll" method="GET">
            <td><button type="submit" class="btn btn-primary" value="<%= each_course['id'] %>" name = "course_id">Enroll</button></td>
          </form>
        <% end %>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<%= javascript_include_tag "_search_controller" %>

<form id="live-search-form" class="form-inline" role="form" action="/entry" method="GET">
  <div class="form-group">
    <label class="filter-col" style="margin-right:0;" for="pref-perpage">Subject:</label>
    <select id="pref-perpage" class="form-control" name="subject">
      <option selected="selected" value="default">Default</option>
        <% @subjects.each do |each_subject| %>
          <option value = "<%= each_subject['university_id'] %>" ><%= each_subject['name'] %></option>
        <% end %>
    </select>
  </div>
  <div class="form-group">
    <label class="filter-col" style="margin-right:0;" for="pref-search">Course:</label>
    <input id="big-search_box" type="text" class="form-control input-sm" id="pref-search" name="course" style=" width:600px">
  </div>
  <div class="form-group">
    <label class="filter-col" style="margin-right:0;" for="pref-search"></label>
    <button type="submit" class="btn btn-default filter-col">Submit</button>
  </div>

  <input type="text" id="myInput" onkeyup="ajaxSearch()" placeholder="Search for courses.." title="Type in a name">
</form>

<form action="/enroll" method="GET">

  <table id="myTable">
    <tr class="header">
      <th style="width:20%;">Name</th>
      <th style="width:55%;">Description</th>
      <th style="width:5%;">ID</th>
      <th style="width:5%;">Code</th>
      <th style="width:5%;">Credit</th>
    </tr>
    <% @courses.each do |each_course| %>
      <tr>
        <td><%= each_course['name'] %></td>
        <td><%= each_course['description'] %></td>
        <td><%= each_course['university_id'] %></td>
        <td><%= each_course['code'] %></td>
        <td><%= each_course['credit'] %></td>

        <td><button type="submit" class="btn btn-primary" value="<%= each_course['id'] %>" name = "course_id">Enroll</button></td>

      </tr>
    <% end %>
  </table>
</form>

app/views/searches/list.js.erb
$("#modal").html('<%= escape_javascript(render("modal")) %>')

// $('#modal').html("<%= j render 'modal' %>");

app/views/searches/new.html.erb
<% provide(:title, "Search") %>
      <div class="container">
      	<div class="row">
          <div class="panel panel-default">
            <div class="panel-body">
              <form id="live-search-form" class="form-inline" role="form" action="/entry" method="GET">
                <div class="form-group">
                  <label class="filter-col" style="margin-right:0;" for="pref-perpage">Subject:</label>
                  <select id="pref-perpage" class="form-control" name="subject">
                    <option selected="selected" value="default">Default</option>
                      <% @subjects.each do |each_subject| %>
                        <option value = "<%= each_subject['university_id'] %>" ><%= each_subject['name'] %></option>
                      <% end %>
                  </select>
                </div>
                <div class="form-group">
                  <label class="filter-col" style="margin-right:0;" for="pref-search">Course:</label>
                  <input id="big-search_box" type="text" class="form-control input-sm" id="pref-search" name="course" style=" width:600px">
                </div>
                <div class="form-group">
                  <label class="filter-col" style="margin-right:0;" for="pref-search"></label>
                  <button type="submit" class="btn btn-default filter-col">Submit</button>
                </div>
              </form>
            </div>
          </div>
      	</div>
        <table class="table">
          <thead class="thead-default">
            <tr>
              <th>ID</th>
              <th>Code</th>
              <th>Name</th>
              <th>Description</th>
              <th>Credits</th>
            </tr>
          </thead>
          <tbody>
            <% @courses.each do |each_course| %>
              <tr>
                <th scope="row"><%= each_course['university_id'] %></th>
                <td><%= each_course['code'] %></td>
                <td><%= each_course['name'] %></td>
                <td><%= each_course['description'] %></td>
                <td><%= each_course['credit'] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>